services:
  - type: web
    name: civic-scan
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn BrillianBengaluru.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: BrillianBengaluru.settings
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: CLOUDINARY_URL
        value: cloudinary://677469849331989:7nRRd5EH4Hf9oOXH1RlTlAXLgOY@dgqm61eqb
      - key: SECRET_KEY 
        value: django-insecure-owyq!#7@^h(3*42+eysd%_c0s$e38h89qt2=-b2!^_vx#g(y58
      - key: ALLOWED_HOSTS
        value: civic-scan.onrender.com
      - key: DATABASE_URL
        value: postgresql://civicscan_db_user:6GH33pfsq6iuCzvZs7DaeqrNqYQxVd4v@dpg-d1hd64emcj7s73dp57tg-a.singapore-postgres.render.com/civicscan_db
