# Generated by Django 5.1 on 2025-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="reports_photos/")),
                (
                    "status",
                    models.CharField(
                        choices=[("clean", "Clean"), ("dirty", "Dirty")], max_length=10
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("review", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
