# Generated by Django 5.1 on 2025-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_user_alter_report_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
